version: "3"

services:

  ssh-proxy:
    build: .
    ports:
      - "2222:2222"

    configs:
      - source: ssh_authorized_keys
        # Mount the file to "/authorized_keys". The image will handle everything else
        target: /authorized_keys
        mode: 0600


configs:
  ssh_authorized_keys:
    file: ./auth/authorized_keys