services:
  host:
    build: .
    deploy:
      resources:
        limits:
          cpus: '10'
          memory: 20G
        reservations:
          cpus: '0.25'
          memory: 256M
    privileged: true
    env_file:
        - .env
    ports:
      - ${open_ssh_port}:${open_ssh_port}
    volumes:
      - ./volumes:/home/
